Fix for multi_json < 1.3.3
Old versions use encode/decode methods, which are deprecated now. But only
in 1.3.3 version they was aliased to dump/load. This patch fixes followin
exception:

couchbase-1.2.0.dp2/lib/couchbase/utils.rb:29:in `build_query': undefined method `dump' for MultiJson:Module (NoMethodError)

Change-Id: I9e409bc7f3141cdc03ea9d0f2aed80851406f34e
Reviewed-on: http://review.couchbase.org/16855
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Chris Anderson <jchris@couchbase.com>