Do not hide ValueFormat reason
In some specific rails environments Value format might be caused by

  NoMethodError: undefined method `dump' for MultiJson:Module

This patch just exposes the original error to allow to report and handle
correspondingly

Change-Id: I4e7f740782ea32cc9d40f0da6b669c2909dca68d
Reviewed-on: http://review.couchbase.org/21744
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Marty Schoch <marty.schoch@gmail.com>
Reviewed-by: Matt Ingenthron <matt@couchbase.com>